name: Suggest Codat Expenses

on:
  workflow_dispatch: {} # Allows manual triggering of the workflow to suggest OpenAPI document

jobs:
  suggest:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-suggestion.yaml@v14.26
    with:
      speakeasy_version: latest
      openapi_docs: |
        - ./yaml/Codat-Expenses.yaml
      openapi_doc_output: ./yaml/Codat-Expenses.yaml
      max_suggestions: 1
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
